admin_admin_homepage:
    path:     /
    defaults: { _controller: AdminAdminBundle:Default:index }

admin_admin_categorie:
    path:     /categorie
    defaults: { _controller: AdminAdminBundle:Categorie:lister }

admin_admin_ajoutcategorie:
    path:     /categorie/ajout
    defaults: { _controller: AdminAdminBundle:Categorie:ajouter }