admin_admin_homepage:
    path:     /test
    defaults: { _controller: AdminAdminBundle:Default:index }

admin_admin_categorie:
    path:     /categorie
    defaults: { _controller: AdminAdminBundle:Categorie:lister }

admin_admin_ajoutcategorie:
    path:     /categorie/ajout
    defaults: { _controller: AdminAdminBundle:Categorie:ajouter }

admin_admin_modifiercategorie:
    path:     /categorie/modifier/{id}
    defaults: { _controller: AdminAdminBundle:Categorie:modifier }
    requirements:
        id: \d+

admin_admin_supprimercategorie:
    path:     /categorie/supprimer/{id}
    defaults: { _controller: AdminAdminBundle:Categorie:supprimer }
    requirements:
        id: \d+

admin_admin_detailcategorie:
    path:     /categorie/detail/{id}
    defaults: { _controller: AdminAdminBundle:Categorie:detailCategorie }
    requirements:
        id: \d+

admin_admin_produits:
    path:     /produits/{idCategorie}
    defaults:
        _controller: AdminAdminBundle:Produit:lister
        idCategorie : null
    requirements:
        id: \d+

admin_admin_ajouter_produit:
    path:     /produit/ajouter
    defaults: { _controller: AdminAdminBundle:Produit:ajouter }

admin_admin_modifier_produit:
    path:     /produit/modifier/{id}
    defaults: { _controller: AdminAdminBundle:Produit:modifier }
    requirements:
        id: \d+

admin_admin_supprimer_produit:
    path:     /produit/supprimer/{id}
    defaults: { _controller: AdminAdminBundle:Produit:supprimer }
    requirements:
        id: \d+

admin_admin_utilisateur:
    path:     /utilisateur_liste
    defaults: { _controller: AdminAdminBundle:Utilisateur:index }

admin_admin_utilisateur_ajout:
    path:     /utilisateur/ajouter
    defaults: { _controller: AdminAdminBundle:Utilisateur:ajout }

admin_admin_utilisateur_modif:
    path:     /utilisateur/modifier/{id}
    defaults: { _controller: AdminAdminBundle:Utilisateur:modif }

admin_admin_utilisateur_suppr:
    path:     /utilisateur/supprimer/{id}
    defaults: { _controller: AdminAdminBundle:Utilisateur:suppr }