admin_admin_homepage:
    path:     /
    defaults: { _controller: AdminAdminBundle:Default:index }

admin_admin_categorie:
    path:     /categorie
    defaults: { _controller: AdminAdminBundle:Categorie:lister }

admin_admin_ajoutcategorie:
    path:     /categorie/ajout
    defaults: { _controller: AdminAdminBundle:Categorie:ajouter }

admin_admin_modifiercategorie:
    path:     /categorie/modifier/{id}
    defaults: { _controller: AdminAdminBundle:Categorie:modifier }
    requirements:
        id: \d+

admin_admin_supprimercategorie:
    path:     /categorie/supprimer/{id}
    defaults: { _controller: AdminAdminBundle:Categorie:supprimer }
    requirements:
        id: \d+

admin_admin_detailcategorie:
    path:     /categorie/detail/{id}
    defaults: { _controller: AdminAdminBundle:Categorie:detailCategorie }
    requirements:
        id: \d+

admin_admin_utilisateur:
    path:     /admin/utilisateur_liste
    defaults: { _controller: AdminAdminBundle:Utilisateur:index }

admin_admin_utilisateur_ajout:
    path:     /admin/utilisateur_ajout
    defaults: { _controller: AdminAdminBundle:Utilisateur:ajout }

admin_admin_utilisateur_modif:
    path:     /admin/utilisateur_modif/{id}
    defaults: { _controller: AdminAdminBundle:Utilisateur:modif }

admin_admin_utilisateur_suppr:
    path:     /admin/utilisateur_suppr/{id}
    defaults: { _controller: AdminAdminBundle:Utilisateur:suppr }
