services:
    admin.adminbundle.subscriber.categoriesubscriber:
        class: Admin\AdminBundle\Subscriber\CategorieSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber }

    admin.adminbundle.subscriber.utilisateursubscriber:
        class: Admin\AdminBundle\Subscriber\UtilisateurSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber }

    admin.adminbundle.subscriber.produitsubscriber:
        class: Admin\AdminBundle\Subscriber\ProduitSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber }
